.TH ncsplash 1 "18th May 2012" "0.2" "ncsplash 0.2"
.SH NAME
ncsplash \- simple ncurses\-based splash screen
.SH SYNOPSIS
ncsplash FIFO LOGO
.SH DESCRIPTION
.B ncsplash
is a simple ncurses-based splash screen which reads strings from a FIFO and prints them to the screen, one at a time.

Additionally, optional logo text may be drawn in the middle of the screen.
.SH OPTIONS
.B ncsplash
does not have any run-time options; however, the text position can be configured at build-time.
.SH SEE ALSO
mkfifo(1)
.SH BUGS
.B ncsplash
has no known bugs.
.SH AUTHOR
Dima Krasner (dima@dimakrasner.com)
